version: 3.4


tasks:
  plan:
    requires:
      vars: [ env ]
    cmds: 
      - tofu init
      - tofu workspace select {{ .env }}
      - tofu plan -out plan.tfplan --var-file={{ .env }}.tfvars

  apply:
    cmds: 
      - tofu apply plan.tfplan