version: 3.4

tasks:
  run:
    cmds:
      - if [ -f mapo.db ]; then rm mapo.db; fi
      - go run main.go

  e2e:
    cmds:
      - ./e2e/e2e.sh

  docker-build:
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
      - Dockerfile
      - .dockerignore
    cmds:
      - docker build -t mapo-api .

  docker-run:
    cmds:
      - task: docker-build
      - |
        docker run \
          -p 5000:5000 \
          -v $PWD/data:/mapo-api/data \
          -e MAPO_API_SQLITE3_FILEPATH=/mapo-api/data/mapo-api.db \
          -e MAPO_API_PORT=5000 \
          mapo-api
      