- name: Install Docker
  hosts: mapo

  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
 
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
 
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present
 
    - name: Install Docker 
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
 
    - name: Start Docker service
      service:
        name: docker
        state: started
 